# Generated by Django 4.2.1 on 2023-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='weight',
        ),
    ]
