# Generated by Django 4.2.1 on 2023-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_remove_pokemon_height_remove_pokemon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
